Django/Learning Django/ClassBasedViews/CBV/CBV/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

Django/Learning Django/ClassBasedViews/CBV/myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('templateview', views.MyTemplateView.as_view(), name='template'),
    path('redirect/<int:pk>', views.Redirect.as_view(), name='redirect'),
    path('redirected-to-me/<int:pk>', views.RedirectedToMe.as_view(), name='redirect_to_me'),    
    path('listview', views.BlogListView.as_view(), name='list'),
    path('detail_view/<int:pk>', views.BlogDetailView.as_view(), name='detail'),
    path('form', views.BasicFormView.as_view(), name='form'),
    path('modelform', views.BlogCreateView.as_view(), name='modelform'),
    path('updateform/<int:pk>', views.BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.DeleteObject.as_view(), name='delete')
]

Django/Learning Django/ClassBasedViews/CBV/myapp/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    another_title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

Django/Learning Django/ClassBasedViews/CBV/myapp/forms.py
from django import forms

class BasicForm(forms.Form):
    name = forms.CharField(max_length=10)
    email = forms.EmailField(required=False)

Django/Learning Django/ClassBasedViews/CBV/myapp/views.py
from django.shortcuts import HttpResponse, render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic.base import RedirectView, TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (CreateView, DeleteView, FormView,
                                       UpdateView)
from django.views.generic.list import ListView

from .forms import BasicForm
from .models import Blog


#  If the request method is not in http_method_names then it will call http_method_not_allowed method.
def home(request):
    html = '<h1>Homepage</h1>'
    return HttpResponse()

class Home(TemplateView):
    template_name = 'home.html'
    def get(self, request):
        return render(request, 'home.html')


class MyTemplateView(TemplateView):
    template_name = 'home.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        context["var"] = 'This is a context data'
        print(context)
        return context

class Redirect(RedirectView):
    pattern_name = 'myapp:redirect_to_me'
    def get_redirect_url(self, *args, **kwargs):
        # logic to implement like no. of clicks in the link
        return super().get_redirect_url(*args, **kwargs)

class RedirectedToMe(TemplateView):
    template_name = 'redirected.html'

class BlogDetailView(DetailView):
    model = Blog
    template_name = "blog_detail.html"

class BlogListView(ListView):
    model = Blog
    template_name = "blog_list.html"
    context_object_name = 'blogs'
    paginate_by = 10
    allow_empty = True
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        return context

class BasicFormView(FormView):
    template_name = 'form.html'
    form_class = BasicForm
    success_url = reverse_lazy('myapp:home')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        return context
    def form_valid(self, form):
        print('valid')
        return super().form_valid(form)

class BlogCreateView(CreateView):
    model = Blog
    fields = ['title']
    success_url = reverse_lazy('myapp:home')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(self.object)
        print(context)
        return context
    
class BlogUpdateView(UpdateView):
    model = Blog
    fields = ['title', 'another_title']
    template_name = 'myapp/blog_form.html'
    success_url = reverse_lazy('myapp:home')


class DeleteObject(DeleteView):
    model = Blog
    success_url = reverse_lazy('myapp:home')
    template_name_suffix = '_confirm_delete'

Django/Learning Django/ClassBasedViews/CBV/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>Homepage</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a href="{% url 'myapp:template' %}" class="nav-link">Template View</a>
        <a href="{% url 'myapp:redirect' pk=5%}" class="nav-link">Redirect</a>
        <a href="{% url 'myapp:list' %}" class="nav-link">List View</a>
        <a href="{% url 'myapp:form' %}" class='nav-link'>Form</a>
        <a href="{% url 'myapp:modelform' %}" class="nav-link">Create Blog</a>
        <a href="{% url 'myapp:update' pk=5 %}" class="nav-link">Update Blog</a>
        <a href="{% url 'myapp:delete' pk=6 %}" class="nav-link">Delete Blog</a>
    </nav>
    <div class='mx-3'>
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

Django/Learning Django/ClassBasedViews/CBV/templates/blog_detail.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}
    {{ object.another_title }}
{% endblock content %}

Django/Learning Django/ClassBasedViews/CBV/templates/blog_list.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}
    {% for blog in blogs %}
        <a href="{% url 'myapp:detail' pk=blog.pk %}">{{ blog|linebreaks }}</a>
    {% endfor %}

    {% include "pagination.html" with page_obj=page_obj %}
{% endblock content %}

Django/Learning Django/ClassBasedViews/CBV/templates/form.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>
{% endblock content %}

Django/Learning Django/ClassBasedViews/CBV/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}
    <h1>This is homepage</h1>
    {{ var }}
{% endblock content %}

Django/Learning Django/ClassBasedViews/CBV/templates/pagination.html
<!DOCTYPE html>
<div>
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">Previous Page</a>
    {% endif %}
    {{page_obj}}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Next Page</a>
    {% endif %}
    
</div>

Django/Learning Django/ClassBasedViews/CBV/templates/redirected.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}
    <h1>Redirected To me</h1>
{% endblock content %}