Social Network/SocialNetwork/SocialNetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('', views.home, name='homepage'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('user/', include('user.urls')),
    path('feed/', include('action.urls')),
    path('__debug__/', include(debug_toolbar.urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Social Network/SocialNetwork/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('upload', views.upload, name='upload'),
    path('<str:user_id>/<str:post_id>/', views.dashboard, name='detail_dash'),
    path('likedstatus/', views.like, name='like'),
    path('all-users/', views.user_list, name='user_list'),
    path('<str:username>/', views.user_detail, name='user_detail'),
    path('follow/accepted', views.follow, name='follow')
]

Social Network/SocialNetwork/user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.conf import settings
from django.urls import reverse
from django.contrib.auth import get_user_model
# Create your models here.

def get_image_file_path(instance, filename):
    return f'{instance.user.id}/post/{filename}'

class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='images', on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=50)
    slug = models.SlugField(blank=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to=get_image_file_path)
    created = models.DateTimeField(auto_now_add=True)
    user_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='image_liked', blank=True)
    user_like_count = models.PositiveIntegerField(default=0, db_index=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("user:detail_dash", kwargs={
            "user_id": self.user.id,
            'post_id':self.id
        })

class Contact(models.Model):
    user_from = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='followed_by', on_delete=models.CASCADE)
    user_to = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='followed_to', on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created_on',)

    def __str__(self):
        return f'{self.user_from} follows {self.user_to}'

user = get_user_model()
user.add_to_class('following', models.ManyToManyField(
    'self', related_name='follower', through=Contact, symmetrical=False))

Social Network/SocialNetwork/user/forms.py
from django import forms
from .models import Image

class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'description', 'image')

Social Network/SocialNetwork/user/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .forms import ImageUploadForm
from django.contrib.auth.decorators import login_required
from .models import Image
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from common.decorators import ajax_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.contrib.auth.models import User
from .models import Contact
from action.utils import create_action

# Create your views here.

def dashboard(request, user_id=None, post_id=None):
    images = Image.objects.all().order_by('-id')
    paginator = Paginator(images, 2)
    page = request.GET.get('page')
    print(request.session.modified)
    try:
        # waw
        images = paginator.page('page')
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        images = paginator.page(paginator.num_pages)
    return render(request, 'user/dashboard.html', {'allimages':images})

@login_required
def upload(request):
    if request.method == 'POST':
        form = ImageUploadForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            new_image = form.save(commit=False)
            new_image.user = request.user
            print(request.user)
            form.save(commit=True)
            return redirect('user:dashboard')
    else:
        form = ImageUploadForm()
    return render(request, 'user/upload.html', {'form':form})

# @ajax_required
@require_POST
def like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    print(action)
    print(request.POST)
    if image_id and action:       
        image = Image.objects.get(id=image_id)
        if action =='Like':
            print('liked')
            image.user_like.add(request.user)
        else:
            print('unliked')
            image.user_like.remove(request.user)
        return redirect('user:dashboard')
    return redirect('user:dashboard')

def user_list(request):
    all_users = User.objects.all()
    return render(request, 'user/user_list.html', {'users':all_users})

def user_detail(request, username):
    user = get_object_or_404(User, username=username)
    followers = user.follower.all()
    return render(request, 'user/user_detail.html', {'user':user, 'followers':followers})

@require_POST
def follow(request):
    user1 = request.user
    user2 = request.POST.get('username')
    user2 = User.objects.get(username=user2)
    # user1.following.add(user2)
    Contact.objects.get_or_create(user_from=user1, user_to=user2)
    create_action(user1, 'followed', user2)
    return redirect('user:user_detail', username=user2)
    

Social Network/SocialNetwork/templates/user/dashboard.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}
    <h1>Dashboard</h1>
    {% for oneimage in allimages %}
        <img src="{% thumbnail oneimage.image 300x0 %}"  alt="">
        <form action="{% url 'user:like' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="action" value={% if request.user in oneimage.user_like.all %} Unlike {% else %} Like {% endif %}>
            <input type="hidden" name="id" value='{{oneimage.id}}'>
            {{oneimage.user_like.count}}
            {{oneimage.user_like.all}}
            <button type='submit'>{% if request.user in oneimage.user_like.all %} Unlike {% else %} Like {% endif %}</button>
        </form>
        <br>
    {% endfor %}
    {% include "pagination.html" with page=allimages%}
{% endblock content %}

Social Network/SocialNetwork/templates/user/upload.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" enctype='multipart/form-data'>
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="UPLOAD">
    </form>
{% endblock content %}

Social Network/SocialNetwork/templates/user/user_detail.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}
    <br>
    firstname = {{ user.first_name }} <br>
    lastname = {{ user.last_name }} <br>
    email = {{ user.email }} <br>
    password = {{ user.password }} <br>
    username = {{ user.username }} <br>
    {% for follower in followers %}
        {{follower}}
    {% endfor %}
    <form action="{% url 'user:follow' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="username" value={{ user }}>
        <input type="submit" value="FOLLOW">
    </form>
{% endblock content %}

Social Network/SocialNetwork/templates/user/user_list.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}
    <br>
    {% for user in users %}
        <a href="{{ user.get_absolute_url }}">{{user}}</a>
        <br>
    {% endfor %}
{% endblock content %}  