Social Network/SocialNetwork/SocialNetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('', views.home, name='homepage'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('user/', include('user.urls')),
    path('feed/', include('action.urls')),
    path('__debug__/', include(debug_toolbar.urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Social Network/SocialNetwork/account/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    # path('login', views.user_login, name='login'),
    # path('login', auth_views.LoginView.as_view(), name='login'),
    # path('logout', auth_views.LogoutView.as_view(), name='logout'),
    # path('password-change', auth_views.PasswordChangeView.as_view(), name='password_change_form'),
    # path('password-change/done', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # path('password-reset', auth_views.PasswordResetView.as_view(), name='password_reset_view'),
    # path('password-rest-done', auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    # path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete')
    path('', include('django.contrib.auth.urls')),
    path('register', views.register, name='register'),
    path('edit', views.edit, name='edit'),
    path('info', views.grab_info, name='info'),
]

Social Network/SocialNetwork/action/urls.py
from django.urls import path
from . import views

app_name = 'action'

urlpatterns = [
    path('', views.feed, name='feed',)
]

Social Network/SocialNetwork/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('upload', views.upload, name='upload'),
    path('<str:user_id>/<str:post_id>/', views.dashboard, name='detail_dash'),
    path('likedstatus/', views.like, name='like'),
    path('all-users/', views.user_list, name='user_list'),
    path('<str:username>/', views.user_detail, name='user_detail'),
    path('follow/accepted', views.follow, name='follow')
]

Social Network/SocialNetwork/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>
</head>
<body>
    <nav>
        <a href="{% url 'account:logout' %}">Logout</a>&nbsp;&nbsp;&nbsp;
        <a href="{% url 'account:login' %}">Login</a>&nbsp;&nbsp;&nbsp;
        <a href="{% url 'account:password_change' %}">Change Password</a>&nbsp;&nbsp;&nbsp;
        <a href="{% url 'account:password_change_done' %}">Password Change Done</a>&nbsp;&nbsp;&nbsp;
        <a href="{% url 'account:password_reset' %}">Password Reset</a>&nbsp;&nbsp;&nbsp;
        <a href="{% url 'account:password_reset_done' %}">Password Reset Done</a>&nbsp;&nbsp;&nbsp;
        <a href="{% url 'account:password_reset_complete' %}">Password Reset Complete</a>&nbsp;&nbsp;&nbsp;
        <a href="{% url 'account:register' %}">Register</a>&nbsp;&nbsp;&nbsp;
        <a href="{% url 'account:edit' %}">Edit Profile</a>&nbsp;&nbsp;&nbsp;
        <a href="{% url 'account:info' %}">Info</a>&nbsp;&nbsp;&nbsp;
        <a href="{% url 'user:upload' %}">Upload Post</a>&nbsp;&nbsp;&nbsp;
        <a href="{% url 'user:dashboard' %}">Dashboard</a>&nbsp;&nbsp;&nbsp;
        <a href="{% url 'user:user_list' %}">User List</a>&nbsp;&nbsp;&nbsp;
        <a href="{% url 'action:feed' %}">Feeds</a>&nbsp;&nbsp;&nbsp;
    </nav>
    {% comment %} {% if message in messages %} {% endcomment %}
        {% for message in messages %}
            {{message}}
        {% endfor %}
    {% comment %} {% endif %} {% endcomment %}
    {% block content %}{% endblock %}
    <br>
    USER - {{request.user}}
</body>
</html>

Social Network/SocialNetwork/templates/pagination.html
<!DOCTYPE html>

<html>
    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <p>Page {{ page.number }} of {{ page.paginator.num_pages }}</p>
    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
</html>